import { useState, useEffect } from 'react';
import { toast } from 'react-toastify';
import { Sparkles, RefreshCw, FileText } from 'lucide-react';
import { FormModal, Button, LoadingSpinner } from '../ui';
import { contactService } from '../../api/services/contactService';
import { generateResponse, generateSubject, getAvailableTemplates } from '../../utils/responseGenerator';

const ContactInquiryReplyModal = ({ isOpen, onClose, inquiry }) => {
  const [formData, setFormData] = useState({
    subject: '',
    message: '',
  });
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});
  const [selectedTemplateId, setSelectedTemplateId] = useState(null);
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const [availableTemplates, setAvailableTemplates] = useState([]);

  // Pre-fill subject and auto-generate response when modal opens or inquiry changes
  useEffect(() => {
    if (isOpen && inquiry) {
      // Generate subject
      const subject = generateSubject(inquiry);
      
      // Auto-generate response message
      const autoMessage = generateResponse(inquiry);
      
      // Get available templates
      const templates = getAvailableTemplates(inquiry);
      setAvailableTemplates(templates);
      
      setFormData({
        subject: subject,
        message: autoMessage,
      });
      setIsAutoGenerated(true);
      setSelectedTemplateId(null);
      setErrors({});
    }
  }, [isOpen, inquiry]);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    // Clear error for this field
    if (errors[name]) {
      setErrors((prev) => {
        const newErrors = { ...prev };
        delete newErrors[name];
        return newErrors;
      });
    }
    // Mark as manually edited if user changes auto-generated content
    if (name === 'message' && isAutoGenerated) {
      setIsAutoGenerated(false);
    }
  };

  const handleTemplateChange = (templateId) => {
    if (!inquiry || !templateId) return;
    
    const generatedMessage = generateResponse(inquiry, templateId);
    setFormData(prev => ({
      ...prev,
      message: generatedMessage,
    }));
    setSelectedTemplateId(templateId);
    setIsAutoGenerated(true);
  };

  const handleAutoGenerate = () => {
    if (!inquiry) return;
    
    const generatedMessage = generateResponse(inquiry);
    const subject = generateSubject(inquiry);
    
    setFormData(prev => ({
      ...prev,
      message: generatedMessage,
      subject: subject,
    }));
    setSelectedTemplateId(null);
    setIsAutoGenerated(true);
    toast.info('Response auto-generated based on inquiry details');
  };

  const validate = () => {
    const newErrors = {};

    if (!formData.subject.trim()) {
      newErrors.subject = 'Subject is required';
    }

    if (!formData.message.trim()) {
      newErrors.message = 'Message is required';
    } else if (formData.message.trim().length < 10) {
      newErrors.message = 'Message must be at least 10 characters';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validate()) {
      return;
    }

    setLoading(true);

    try {
      await contactService.reply(inquiry.id, {
        subject: formData.subject.trim(),
        message: formData.message.trim(),
      });

      toast.success('Reply sent successfully!');
      
      // Reset form
      setFormData({
        subject: '',
        message: '',
      });
      setErrors({});

      // Close modal after a short delay
      setTimeout(() => {
        onClose();
      }, 1000);
    } catch (error) {
      console.error('Error sending reply:', error);
      toast.error(
        error.response?.data?.message || 
        error.response?.data?.errors?.message?.[0] ||
        'Failed to send reply. Please try again.'
      );
    } finally {
      setLoading(false);
    }
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  const formatCurrency = (amount) => {
    if (!amount) return 'Not specified';
    return `₱${parseFloat(amount).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  };

  if (!inquiry) return null;

  const inquiryName = inquiry.name || `${inquiry.first_name || ''} ${inquiry.last_name || ''}`.trim() || 'Customer';

  return (
    <FormModal
      isOpen={isOpen}
      onClose={onClose}
      title="Reply to Inquiry"
      size="lg"
    >
      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Inquiry Context */}
        <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4 space-y-3">
          <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3">
            Inquiry Details
          </h3>
          <div className="grid grid-cols-2 gap-3 text-sm">
            <div>
              <span className="font-medium text-gray-600 dark:text-gray-400">Name:</span>
              <span className="ml-2 text-gray-900 dark:text-white">{inquiryName}</span>
            </div>
            <div>
              <span className="font-medium text-gray-600 dark:text-gray-400">Email:</span>
              <span className="ml-2 text-gray-900 dark:text-white">{inquiry.email}</span>
            </div>
            <div>
              <span className="font-medium text-gray-600 dark:text-gray-400">Event Type:</span>
              <span className="ml-2 text-gray-900 dark:text-white">{inquiry.event_type || 'N/A'}</span>
            </div>
            <div>
              <span className="font-medium text-gray-600 dark:text-gray-400">Event Date:</span>
              <span className="ml-2 text-gray-900 dark:text-white">
                {inquiry.date_of_event ? formatDate(inquiry.date_of_event) : 'Not specified'}
              </span>
            </div>
            <div>
              <span className="font-medium text-gray-600 dark:text-gray-400">Venue:</span>
              <span className="ml-2 text-gray-900 dark:text-white">{inquiry.preferred_venue || 'N/A'}</span>
            </div>
            <div>
              <span className="font-medium text-gray-600 dark:text-gray-400">Budget:</span>
              <span className="ml-2 text-gray-900 dark:text-white">{formatCurrency(inquiry.budget)}</span>
            </div>
          </div>
          {inquiry.message && (
            <div className="mt-3 pt-3 border-t border-gray-200 dark:border-gray-700">
              <span className="font-medium text-gray-600 dark:text-gray-400 text-sm block mb-1">
                Original Message:
              </span>
              <p className="text-sm text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-900 p-2 rounded border border-gray-200 dark:border-gray-700">
                {inquiry.message}
              </p>
            </div>
          )}
        </div>

        {/* Template Selection Section */}
        <div className="bg-blue-50 dark:bg-blue-900/20 rounded-lg p-4 border border-blue-200 dark:border-blue-800">
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-blue-600 dark:text-blue-400" />
              <h3 className="text-sm font-semibold text-blue-900 dark:text-blue-100">
                Response Templates
              </h3>
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleAutoGenerate}
              className="text-xs"
            >
              <RefreshCw className="w-3 h-3 mr-1" />
              Auto-Generate
            </Button>
          </div>
          
          <div className="flex flex-wrap gap-2">
            {availableTemplates.slice(0, 5).map((template) => (
              <button
                key={template.id}
                type="button"
                onClick={() => handleTemplateChange(template.id)}
                className={`px-3 py-1.5 text-xs rounded-md border transition-colors ${
                  selectedTemplateId === template.id
                    ? 'bg-blue-600 text-white border-blue-600 dark:bg-blue-700 dark:border-blue-700'
                    : 'bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border-gray-300 dark:border-gray-600 hover:bg-blue-50 dark:hover:bg-blue-900/30'
                }`}
              >
                {template.name}
              </button>
            ))}
            {availableTemplates.length > 5 && (
              <select
                value={selectedTemplateId || ''}
                onChange={(e) => handleTemplateChange(e.target.value)}
                className="px-3 py-1.5 text-xs rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">More templates...</option>
                {availableTemplates.slice(5).map((template) => (
                  <option key={template.id} value={template.id}>
                    {template.name}
                  </option>
                ))}
              </select>
            )}
          </div>
          
          {isAutoGenerated && (
            <div className="mt-2 flex items-center gap-1 text-xs text-blue-600 dark:text-blue-400">
              <Sparkles className="w-3 h-3" />
              <span>Auto-generated response (you can edit)</span>
            </div>
          )}
        </div>

        {/* Subject Field */}
        <div>
          <label
            htmlFor="subject"
            className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2"
          >
            Subject <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            id="subject"
            name="subject"
            value={formData.subject}
            onChange={handleChange}
            className={`w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:bg-gray-800 dark:text-white dark:border-gray-600 ${
              errors.subject ? 'border-red-500' : 'border-gray-300'
            }`}
            placeholder="Enter email subject"
            disabled={loading}
          />
          {errors.subject && (
            <p className="mt-1 text-sm text-red-500">{errors.subject}</p>
          )}
        </div>

        {/* Message Field */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label
              htmlFor="message"
              className="block text-sm font-medium text-gray-700 dark:text-gray-300"
            >
              Message <span className="text-red-500">*</span>
            </label>
            {isAutoGenerated && (
              <span className="text-xs text-blue-600 dark:text-blue-400 flex items-center gap-1">
                <FileText className="w-3 h-3" />
                Auto-generated
              </span>
            )}
          </div>
          <textarea
            id="message"
            name="message"
            value={formData.message}
            onChange={handleChange}
            rows={10}
            className={`w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:bg-gray-800 dark:text-white dark:border-gray-600 resize-y ${
              errors.message ? 'border-red-500' : 'border-gray-300'
            } ${isAutoGenerated ? 'bg-blue-50/50 dark:bg-blue-900/10' : ''}`}
            placeholder="Type your reply message here or use a template above..."
            disabled={loading}
          />
          {errors.message && (
            <p className="mt-1 text-sm text-red-500">{errors.message}</p>
          )}
          <div className="mt-1 flex items-center justify-between">
            <p className="text-xs text-gray-500 dark:text-gray-400">
              {formData.message.length} characters
            </p>
            {formData.message.trim().length > 0 && !isAutoGenerated && (
              <p className="text-xs text-gray-500 dark:text-gray-400 italic">
                Custom message
              </p>
            )}
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex justify-end gap-3 pt-4 border-t border-gray-200 dark:border-gray-700">
          <Button
            type="button"
            variant="outline"
            onClick={onClose}
            disabled={loading}
          >
            Cancel
          </Button>
          <Button
            type="submit"
            variant="primary"
            disabled={loading}
          >
            {loading ? (
              <span className="flex items-center gap-2">
                <LoadingSpinner size="sm" />
                Sending...
              </span>
            ) : (
              'Send Reply'
            )}
          </Button>
        </div>
      </form>
    </FormModal>
  );
};

export default ContactInquiryReplyModal;

